### ISSUE TITLE
Add link to clients and categories to top nav bar

### ISSUE THREAD

**Issue by gstark** [tiy-tpa-ruby-q3-2015/Hours#3]
The top navigation bar is a bit sparse. Add links to view clients and categories to the nav.

**Comment by myk27x** [comment]
https://github.com/tiy-tpa-ruby-q3-2015/Hours/pull/12

**Comment by myk27x** [comment]
issue-3 resolved

Pull request link: https://github.com/tiy-tpa-ruby-q3-2015/Hours/pull/12
