### ISSUE TITLE
Project description supports markdown formatting.

### ISSUE THREAD

**Issue by gstark** [tiy-tpa-ruby-q3-2015/Hours#5]
When showing the project description, support markdown formatting

**Comment by mark-smithtb** [comment]
The project description already supports markdown formatting. There is a helper method in markdown_helper.rb called markdown that takes a argument of the text that may include markdown. It creates a new instance renderer based on the options defined and sets that to renderer. It then creates a new instance of Markdown which based on the renderer and the extensions parses the input and generate the out put html. The final line Redcarpet uses a render method on markdown to pass it the text to be rendered and out puts it as html_safe.
